export const businesses = [
  {
    id: 1,
    name: 'Alpha Inc',
    phoneNumber: '555-9929-4363',
    businessCity: 'New York',
    businessState: 'NY',
    isPublic: true,
  },
  {
    id: 2,
    name: 'Beta LLC',
    phoneNumber: '555-3259-4796',
    businessCity: 'Los Angeles',
    businessState: 'CA',
    isPublic: false,
  },
  {
    id: 3,
    name: 'Gamma Co',
    phoneNumber: '555-1457-2741',
    businessCity: 'Chicago',
    businessState: 'IL',
    isPublic: true,
  },
  {
    id: 4,
    name: 'Delta Ltd',
    phoneNumber: '555-7706-4700',
    businessCity: 'Houston',
    businessState: 'TX',
    isPublic: false,
  },
  {
    id: 5,
    name: 'Epsilon Corp',
    phoneNumber: '555-5782-4627',
    businessCity: 'Phoenix',
    businessState: 'AZ',
    isPublic: true,
  },
  {
    id: 6,
    name: 'Zeta PLC',
    phoneNumber: '555-3907-5584',
    businessCity: 'Philadelphia',
    businessState: 'PA',
    isPublic: true,
  },
  {
    id: 7,
    name: 'Eta S.A.',
    phoneNumber: '555-7847-8896',
    businessCity: 'San Antonio',
    businessState: 'TX',
    isPublic: true,
  },
  {
    id: 8,
    name: 'Theta GmbH',
    phoneNumber: '555-5635-5711',
    businessCity: 'San Diego',
    businessState: 'CA',
    isPublic: true,
  },
  {
    id: 9,
    name: 'Iota SRL',
    phoneNumber: '555-2582-6007',
    businessCity: 'Dallas',
    businessState: 'TX',
    isPublic: false,
  },
  {
    id: 10,
    name: 'Kappa AG',
    phoneNumber: '555-7226-6134',
    businessCity: 'San Jose',
    businessState: 'CA',
    isPublic: true,
  },
  {
    id: 11,
    name: 'Lambda Group',
    phoneNumber: '555-2317-2282',
    businessCity: 'New York',
    businessState: 'NY',
    isPublic: true,
  },
  {
    id: 12,
    name: 'Mu Designs',
    phoneNumber: '555-3900-6964',
    businessCity: 'Los Angeles',
    businessState: 'CA',
    isPublic: true,
  },
  {
    id: 13,
    name: 'Nu Technologies',
    phoneNumber: '555-5811-5498',
    businessCity: 'Chicago',
    businessState: 'IL',
    isPublic: true,
  },
  {
    id: 14,
    name: 'Xi Services',
    phoneNumber: '555-7905-7174',
    businessCity: 'Houston',
    businessState: 'TX',
    isPublic: true,
  },
  {
    id: 15,
    name: 'Omicron Solutions',
    phoneNumber: '555-1692-6637',
    businessCity: 'Phoenix',
    businessState: 'AZ',
    isPublic: true,
  },
  {
    id: 16,
    name: 'Pi Engineering',
    phoneNumber: '555-5190-7342',
    businessCity: 'Philadelphia',
    businessState: 'PA',
    isPublic: true,
  },
  {
    id: 17,
    name: 'Rho Systems',
    phoneNumber: '555-7570-5141',
    businessCity: 'San Antonio',
    businessState: 'TX',
    isPublic: false,
  },
  {
    id: 18,
    name: 'Sigma Creative',
    phoneNumber: '555-6801-5833',
    businessCity: 'San Diego',
    businessState: 'CA',
    isPublic: true,
  },
  {
    id: 19,
    name: 'Tau Networks',
    phoneNumber: '555-1626-8201',
    businessCity: 'Dallas',
    businessState: 'TX',
    isPublic: true,
  },
  {
    id: 20,
    name: 'Upsilon Factory',
    phoneNumber: '555-3799-8190',
    businessCity: 'San Jose',
    businessState: 'CA',
    isPublic: true,
  },
];
